@startuml
'left to right direction

actor Operator
participant Frontend
participant Coordinator
participant "Mutant\nAnalyzer" as mutana
participant "Single\nTester" as singletest
participant "Single\nCode Mutator" as singlemut
participant Report

== Analyze ==

Operator -> Frontend : src,buildenv
activate Frontend
Frontend -> Coordinator : passe over info from user

Coordinator -> mutana : src,buildenv
activate mutana
mutana -> mutana : discover possible\nmutants
Coordinator <-- mutana : send over data
deactivate mutana

Frontend <-- Coordinator : report success/fail of analyse
deactivate Frontend

Operator <-- Frontend : prettify the result

== Classify ==

Operator -> Frontend : control parameters\nmutation ops
activate Frontend
Frontend -> Coordinator : configure
activate Coordinator

loop all mutants from config
Coordinator -> singletest : push mutant
activate singletest
singletest -> singlemut : mutate src
singletest <-- singlemut
singletest -> singletest : compile program
singletest -> singletest : run test suite
Coordinator <-- singletest : report classification\nfor mutant
deactivate singletest
end

Frontend <-- Coordinator : report status of classifying
deactivate Coordinator

Operator <-- Frontend
deactivate Frontend

== Report ==

Operator -> Frontend : all classified mutants
activate Frontend

Frontend -> Report : config data
activate Report

Report -> Coordinator : pull data
activate Coordinator
Report <-- Coordinator : all mutants
deactivate Coordinator

Report -> Report : create report
Frontend <-- Report : where to find report
deactivate Report

Operator <-- Frontend : open report
deactivate Frontend

@enduml
